### ISSUE TITLE
[Bug] Rescaled TV's clips through floor/objects

### ISSUE THREAD

**Issue by JohnMetroid** [DeathWrench/ScaleableTelevision#1]
![image](https://github.com/DeathWrench/ScaleableTelevision/assets/139426529/b66711d2-8a56-4bfc-9716-4b23c08d8745)

**Comment by DeathWrench** [comment]
I recommend using one of these mods for now [BetterDecorPlacement](https://thunderstore.io/c/lethal-company/p/ViViKo/BetterDecorPlacement/) or [Build Anywhere](https://thunderstore.io/c/lethal-company/p/Vegasx/Build_Anywhere/) so it can be mounted on a wall at least.
